services:
  # ローカル開発環境
  app:
    build:
      context: ../../../
      dockerfile: nomoca-kagawa-web/infrastructure/docker/Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "3000:3000"
    env_file:
      - ../../frontend/.env
    volumes:
      - ../../frontend/src:/app/src
      - ../../frontend/public:/app/public
      - ../../frontend/next.config.mjs:/app/next.config.mjs
      - ../../frontend/tailwind.config.ts:/app/tailwind.config.ts
      - ../../frontend/tsconfig.json:/app/tsconfig.json
      - ../../frontend/postcss.config.mjs:/app/postcss.config.mjs
    command: pnpm dev

networks:
  nomoca-network:
    external: true
    name: nomoca-network

